# ---- Étape 1 : Base Node ----
FROM node:22-slim

WORKDIR /app

# Copier package.json et package-lock.json pour cache npm
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# Copier le code source
COPY . .

# Exposer le port sur lequel l'app Node/Angular tourne
EXPOSE 4200

# Lancer l'application
CMD ["npm", "run", "start"]
